Description: This CloudFormation template creates a Site-to-Site VPN configuration in AWS. It provisions the necessary resources for establishing a VPN connection between a customer's on-premises network (Customer Gateway) and an AWS Virtual Private Cloud (VPC) (Virtual Private Gateway). 
#Do not forget to enable route propagation in route table & define static routes in VPN connection.

Parameters:
  CustomerGatewayIpAddress:
    Description: IP address of the customer gateway
    Type: String
  CustomerGatewayName:
    Description: Name for the Customer Gateway
    Type: String
  CustomerGatewayBgpAsn:
    Description: BGP ASN of the customer gateway
    Type: String
    Default: 65000
  VirtualPrivateGatewayId:
    Description: ID of an existing Virtual Private Gateway
    Type: String
  VPNConnectionName:
    Description: Name for the VPN Connection
    Type: String

Resources:
  CustomerGateway:
    Type: AWS::EC2::CustomerGateway
    Properties:
      BgpAsn: !Ref CustomerGatewayBgpAsn
      IpAddress: !Ref CustomerGatewayIpAddress
      Type: ipsec.1
      Tags:
        - Key: Name
          Value: !Ref CustomerGatewayName

  VPNConnection:
    Type: AWS::EC2::VPNConnection
    Properties:
      Type: ipsec.1
      CustomerGatewayId: !Ref CustomerGateway
      VpnGatewayId: !Ref VirtualPrivateGatewayId
      StaticRoutesOnly: true
      Tags:
        - Key: Name
          Value: !Ref VPNConnectionName